In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,-3],
             [-5,-6,7]])
a

array([[ 1,  2, -3],
       [-5, -6,  7]])

In [6]:
a + 2

array([[ 3,  4, -1],
       [-3, -4,  9]])

In [7]:
def naive_relu(x):
    assert len(x.shape) == 2
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x
naive_relu(a)

array([[1, 2, 0],
       [0, 0, 7]])

In [8]:
np.maximum(a, 0)

array([[1, 2, 0],
       [0, 0, 7]])

In [9]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

naive_add(a,a+2)

array([[  4,   6,  -4],
       [ -8, -10,  16]])

In [10]:
a = np.arange(32*10).reshape((32,10))
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [11]:
b = np.arange(10).reshape((1,10))
b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [12]:
print(a.shape)
print(b.shape)

(32, 10)
(1, 10)


In [ ]:
a + b

In [ ]:
a + (b+5)