In [4]:
import numpy as np

In [7]:
a = np.arange(27).reshape(3,3,3)
print(a.ndim)# number of dimension/rank 3D
print(a.shape)# number of axis in each dimension
print(a.size)# number elements
a

3
(3, 3, 3)
27


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
a = np.arange(3*3*3).reshape(3,3,3)
print(a.ndim)# number of dimension/rank 3D
print(a.shape)# number of axis in each dimension
print(a.size)# number elements
a

3
(3, 3, 3)
27


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [11]:
# 4 pictures resoulation 8X8
a = np.arange(4*8*8).reshape(4,8,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [ ]:
# 4 pictures resoulation 8X8
a = np.arange(4*8*8).reshape(4,8,8)
a

In [13]:
np.random.randint(0,255,(10,8,8))

array([[[ 93, 102, 203, 182, 109, 226, 222,  76],
        [168,  39, 203,  76, 222,  87,  79,  38],
        [237, 213, 240,  40,  86, 221, 136, 163],
        [110, 119, 120, 185, 120,  26,  49, 234],
        [192,  62, 107, 183, 175,  77, 104, 130],
        [157,  31, 248,  98, 154, 245, 178, 144],
        [187, 142,  48, 113,  17, 250, 167, 118],
        [204, 205, 201, 198, 229,  37,   0, 174]],

       [[205, 198, 192, 161, 178,  39, 171, 142],
        [214, 121,  73, 231,  20, 202, 108,  21],
        [ 83,  33,  72,  15, 206,   5, 211, 221],
        [ 59, 116,  78, 192,  84,  45,  95,  88],
        [ 35, 121,  93,  92,  97, 200, 187,  73],
        [163,  72,  69, 248,  87, 168,   0, 223],
        [ 88, 235, 167, 144, 214, 146, 176,  75],
        [  8, 232, 129, 172,   4,  46,  30, 140]],

       [[ 38,  43,  63, 160, 178, 206,  67, 199],
        [  4,   8,  26,  75,   8, 127,   3,  26],
        [115,  37,  45, 166, 125, 253, 224, 139],
        [ 94, 192, 188,  23,  28, 142, 169, 20

In [3]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# create numpy array

In [17]:
a = np.array([1,2,3])
print(a)
display(a)

[1 2 3]


array([1, 2, 3])

In [19]:
a = np.array((1,2,3))
print(a)
display(a)

[1 2 3]


array([1, 2, 3])

In [24]:
a = np.array([[1,2,3],
             [4,5,6]])
display(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
a = np.array([[1,2,3],
             [4,5,6]])
display(a)
print(a.shape)
a[:,-2:]

array([[1, 2, 3],
       [4, 5, 6]])

(2, 3)


array([[2, 3],
       [5, 6]])

# How to create a basic array

* np.array(),
* np.zeros(), 
* np.ones(),
* np.empty(), 
* np.arange(), 
* np.linspace()

In [34]:
display(np.zeros(10))
display(np.ones(10))
display(np.empty(10))


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
np.linspace(1,60,3)

array([ 1. , 30.5, 60. ])

In [46]:
a = np.arange(3*3*3).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [47]:
np.ones_like(a)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [49]:
np.zeros_like(a)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [50]:
np.empty_like(a)

array([[[            46193328,                    0,
              140141512295632],
        [ 3461208976345099791,      140141514522368,
              140141512295568],
        [-7244815879574477975,      140141514452096,
              140141512294864]],

       [[ 6279874319330613891,      140141514433792,
              140141512296720],
        [-7500444324455017019,      140141514427280,
              140141512297168],
        [ 6893097100870067911,      140141514568080,
              140142232039184]],

       [[ 4313671982764067948,      140141514353872,
              140141512298064],
        [ 7123815352990065129,      140141514471376,
              140141512298000],
        [ 2176098950188350803,      140141514568160,
                          368]]])

In [52]:
np.ones((10,10),dtype=np.int64)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [53]:
np.ones((10,10),dtype="str")

array([['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1']], dtype='<U1')

In [57]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [75]:
np.arange(3*3*3).reshape(-1,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# arg

In [86]:
#              0 1 2  3 4 5
a = np.array([1,7,20,0,4,3])
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))
print(a[3],a[0],a[5],a[4],a[1],a[2])

print(a[a.argsort()])

2
3
[3 0 5 4 1 2]
0 1 3 4 7 20
[ 0  1  3  4  7 20]


In [84]:
labels = ['cat','dog','apple','orange']
prediction = [70,100,100,15]
index = np.argmax(prediction)#max index probability
print(labels[index])

dog


# Concatinate

In [88]:
a = np.arange(1,11).reshape(5,2)
b = np.arange(11,21).reshape(5,2)
display(a)
display(b)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [90]:
np.concatenate((a,b))# axis defualt 0

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [91]:
np.concatenate((a,b),axis=1)# axis defualt 0

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [94]:
np.stack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [97]:
display(a,b)
np.stack((a,b),axis=1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

array([[[ 1,  2],
        [11, 12]],

       [[ 3,  4],
        [13, 14]],

       [[ 5,  6],
        [15, 16]],

       [[ 7,  8],
        [17, 18]],

       [[ 9, 10],
        [19, 20]]])

In [98]:
np.hstack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [100]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [101]:
a = np.arange(2*2*2).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [102]:
a.sum()

28

In [103]:
display(a)
a.sum(axis=0)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 4,  6],
       [ 8, 10]])

In [104]:
display(a)
a.sum(axis=1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 2,  4],
       [10, 12]])

In [105]:
display(a)
a.sum(axis=2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 1,  5],
       [ 9, 13]])

# Slicing, Indexing, Fancy Slicing, Boolean Slicing

In [111]:
a = np.arange(4*4).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [113]:
print(a[0])
print(a[2])

[0 1 2 3]
[ 8  9 10 11]


In [116]:
display(a)
display(a[::2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [119]:
display(a)
display(a[[1,2,0,1,1,1]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7]])

In [121]:
display(a)
a % 2 == 0

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [129]:
b = np.arange(1,7)
display(b)
display(b[[False,  True, False,  True, False,  True]])
b % 2 == 0

array([1, 2, 3, 4, 5, 6])

array([2, 4, 6])

array([False,  True, False,  True, False,  True])

In [130]:
b = np.arange(1,7)
display(b)
b[b % 2 == 0]

array([1, 2, 3, 4, 5, 6])

array([2, 4, 6])

In [132]:
display(a)
a[a % 2 == 0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [133]:
display(a)
a[(a % 2 == 0) & (a % 4 == 0)]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([ 0,  4,  8, 12])

In [134]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [135]:
b = a
print(id(a))
print(id(b))

140141492055184
140141492055184


In [137]:
a[0][0] = 20
a

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [138]:
b

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [139]:
c = a.copy()

In [140]:
display(a)
display(b)
display(c)

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [141]:
a[0][0] = 200
display(a)
display(b)
display(c)

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

array([[200,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

array([[20,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])